/**:
  ros__parameters:
    mode: "run"                                           # "run" | "debug"

    # DEBUG PARAMETERS (only used if mode=="debug")
    console_menu:         false                           # true => enable stdin menu
    debug.P_N2B:          [0.187, 0., 0.22]               # offset of manipulator base link in the mobile base frame (x,y,z) in meters
    debug.q_deg:          [0., -90., -90., -0., 90., 0.]  # initial joint positions (deg)
    debug.theta_N2B_deg:  [0., 0., 0.]                    # orientation of manipulator base link in the mobile base frame (r,p,y) in degrees
    debug.theta_W2N_deg:  [0., 0., 0.]                    # orientation of world frame in the map frame (r,p,y) in degrees
    debug.u_star:         [0., 0., 0., 0., 0., 0.]        # desired end-effector twist (vx,vy,vz,wx,wy,wz) in m/s and rad/s
    debug.dotq_prev:      [0., 0., 0., 0., 0., 0.]        # previous joint velocities (rad/s)
    debug.step_once:      false                           # if true, perform one control step and then stop

    # RUNTIME PARAMETERS
    topics:
      joint_state: "/joint_states"                # joint state topic for the robotic arm
      twist_cmd:   "/mobile_manipulator/cmd_vel"  # twist command topic for the whole body platform
      cmd_vel:     "/cmd_vel"                     # command velocity topic for the mobile base
      q_speed:     "/manipulator/js_cmd_vel"      # joint speed topic for the manipulator
      arm_vel:     "/manipulator/cmd_vel"         # arm speed topic

    control:
      dt: 0.005                                   # control period

    qp:
      use_native: true                            # use native qp solver (true) or matlab generated (false)
      cols: [1,2,3,4,5,6,7,8,12]                  # columns of jacobian (ignore vz, wx, wy for a planar mobile base)
      beta_arm: 0.001                             # weight for the manipulator joints (regularization penalty, penalized less)  
      alpha_xy: 0.002                             # weight for the base translation (penalized more)
      alpha_yaw: 0.002                            # weight for the base rotation (penalized more)
      w_lin: 1.0                                  # weight for the linear velocity tracking
      w_ang: 1.0                                  # weight for the angular velocity tracking (set to 0.0 if no orientation constraints)
      nu: 0.001                                   # weight for the slack variable (soft constraint for twist tracking)
      max_dotq: 1.0                               # maximum joint speed (rad/s)
      max_V: 0.2                                  # maximum linear velocity of the mobile base (m/s)
      max_Omegaz: 0.2                             # maximum angular velocity of the mobile base (rad/s)

    limits:
      qmin: [-0.1745, -2.0944, -2.3562, -2.3562, -0.0000, -1.5708]  # joint position limits (rad) min boundaries [-10 -120 -135 -135  -0 -180]
      qmax: [+1.5708, -1.4835, +0.0000, +1.5708, +1.9199, +1.5708]  # joint position limits (rad) max boundaries [+90  -85    0   90 110  180]
      qddot_max: 2.0                              # maximum joint acceleration (rad/s^2)
      a_lin_max: 1.0                              # maximum linear acceleration (m/s^2)
      alpha_max: 1.0                              # maximum angular acceleration (rad/s^2)

    kinematics:
      P_N2B:     [0.187, 0.0, 0.22]               # offset of manipulator base link in the mobile base frame (x,y,z)
      theta_N2B: [0.0,   0.0, 0.00]               # orientation of manipulator base link in the mobile base frame (r,p,y)

    frames:
      map:       "map"                            # fixed world frame 
      base:      "mobile_base"                    # mobile base frame
      base_link: "world_ur"                       # manipulator base link frame